export enum FlowerType {
	Allium = "allium",
	Cornflower = "cornflower",
	Dandelion = "dandelion",
	Fern = "fern",
	Grass = "grass",
	Houstonia = "houstonia",
	LilyOfTheValley = "lily_of_the_valley",
	Orchid = "orchid",
	Oxeye = "oxeye",
	Paeonia = "paeonia",
	Poppy = "poppy",
	Rose = "rose",
	Sunflower = "sunflower",
	Syringa = "syringa",
	TulipOrange = "tulip_orange",
	TulipPink = "tulip_pink",
	TulipRed = "tulip_red",
	TulipWhite = "tulip_white"
}
