export enum CC {
	Aqua = "§b",
	Black = "§0",
	Blue = "§9",
	Bold = "§l",
	DarkAqua = "§3",
	DarkBlue = "§1",
	DarkGreen = "§2",
	DarkGrey = "§8",
	DarkPurple = "§5",
	DarkRed = "§4",
	Gold = "§6",
	Yellow = "§e",
	Green = "§a",
	Grey = "§7",
	Italic = "§o",
	LightPurple = "§d",
	Red = "§c",
	Reset = "§r",
	Strikethrough = "§m",
	Underline = "§n",
	White = "§f"
}
